docker installation guide improvements
OriginTrail/dkg-docs pull request #4
Opened 2021-08-06 20:35 UTC by Valcyclovir

This is BRX from the community channel reporting in, I am bringing in some changes to Milian's guide on his complete installation guide. This guide is being widely shared among the community and making sure it is updated frequently is crucial ! Thanks.

2022-02-10 16:45 UTC, Valcyclovir commented
Please review the previous changes whenever possible. This guide by Milian is widely used by new node runners and I will try to keep it updated as we go.

2022-02-11 03:17 UTC, Valcyclovir commented
Arch Linux guide tested using EndeavourOS

2022-02-12 03:50 UTC, jlsam requested changes
There are many FTP programs that support sftp.
Filezilla is probably the most well known, but I suggest it should be mentioned as an example only.

To use just a server name in Files, the user needs to have a properly set up ~/.ssh/config file. That is beyond the scope of this guide. Perhaps a more 'manual' example like sftp://user@ip would be more clear

2022-02-13 03:55 UTC, Valcyclovir commented
@jlsam Thanks for the feedback ! Since Filezilla is FOSS, I didn't mind straight up suggesting it but you are right, I changed that part a little. Turns out it's also available for Ubuntu (and other Linux platforms) so it will be the go-to suggestion for anyone struggling to move the file over.

2022-02-13 03:58 UTC, Valcyclovir commented
Updates today:
- Added blazegraph support for Arch users to reflect most recent updates
- Removed manual installation guide for dockerless since it's outdated (nohub and forever no longer needed), no reasons not to use calvin's one script install
- Updated suggested way to move graphDB to test node server

2022-02-14 11:09 UTC, djordjekovac approved these changes

2022-02-14 12:42 UTC, NZT48 commented on dkg-v6-upcoming-version/setup-instructions-dockerless.md
>  ****\
Please remove this

2022-02-14 14:12 UTC, NZT48 approved these changes

2022-02-14 14:13 UTC, merged